### ISSUE TITLE
Strange problem on macOS

### ISSUE THREAD

**Issue by Shrapnel21** [drhelius/Gearcoleco#4] opened 2021-09-07 18:46 UTC
Hi and, first of all, thanks for providing a macOS version! =)
I downloaded the latest version of Gearcoleco today and, quite strangely, the app just doesn't open. No errors, no crashes, nothing at all: it's just like that, I double-click it and nothing happens. Additional info: Intel CPU, macOS 10.15.7, already authorized Gearcoleco.
Any idea?
Thanks in advance! =)

**Comment by drhelius** [comment] 2021-09-07 21:53
That’s weird.
Did you try right-clicking or Control-clicking the app and selecting “Open”?

**Comment by Shrapnel21** [comment] 2021-09-07 21:55
Sure, that's what I did two times right after installing it to 'authorize' it.
Tried that again later, too, when I saw that double-clicking it did nothing, but still no dice.
There must be something wrong with my system that I can't still find out, I'll keep checking.

**Comment by drhelius** [comment] 2021-09-08 09:39
Sorry, you're completely right, I was able to reproduce it my self.

**Comment by Shrapnel21** [comment] 2021-09-08 09:41
Oh well, sh1t happens, right? =)
I'm sure you'll solve that soon, thanks again for looking into it!

**Comment by drhelius** [comment] 2021-09-08 09:56
I don't know what's going on, I was able to upload it again, download it to my Mac and get it working by right clicking and selecting "Open" after giving access in some pop-ups that appeared.

Could you try it again? 

https://github.com/drhelius/Gearcoleco/releases/tag/1.0.0

**Comment by Shrapnel21** [comment] 2021-09-08 10:01
Same as before.
If it can help, here's what I get if I try opening it from the Terminal:

LSOpenURLsWithRole() failed with error -10810 for the file

**Comment by drhelius** [comment] 2021-09-08 10:04
Did you use the new version I uploaded just now? I was able to reproduce the error with the old bundle but it's working for me with the new bundle I just uploaded.

It is definitely macOS gatekeeper preventing it to open.

**Comment by Shrapnel21** [comment] 2021-09-08 10:14
Been digging a little and found a crash log, here it is:

- - - - -
Process:               gearcoleco [6463]
Path:                  /private/var/folders/*/Gearcoleco.app/Contents/MacOS/gearcoleco
Identifier:            gearcoleco
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        bash [6462]
User ID:               501

Date/Time:             2021-09-08 12:10:14.893 +0200
OS Version:            Mac OS X 10.15.7 (19H1323)
Report Version:        12
Anonymous UUID:        E2DAB20E-07ED-8A95-C824-97B4344E85E3


Time Awake Since Boot: 4400 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @Gearcoleco.app/Contents/MacOS/libSDL2-2.0.0.dylib
  Referenced from: /private/var/folders/*/Gearcoleco.app/Contents/MacOS/./gearcoleco
  Reason: image not found

Binary Images:
       0x102f6f000 -        0x10304effb +gearcoleco (0) <D5ACB4DE-49BA-3152-A6B9-C407B86AD47C> /var/folders/*/Gearcoleco.app/Contents/MacOS/gearcoleco
       0x10b180000 -        0x10b212267  dyld (750.7) <FCEF919F-F7F8-3C1A-B208-7ECDCB5EA674> /usr/lib/dyld
    0x7fff36e4d000 -     0x7fff36e4dfff  com.apple.Cocoa (6.11 - 23) <33FF1A89-BE2C-3D3D-8A31-5EB43F328706> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff39d03000 -     0x7fff39d47ffb  com.apple.CoreVideo (1.8 - 344.3) <5314E70D-325F-3E98-99FC-00FDF520747E> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fff3aae6000 -     0x7fff3ab8aff3  com.apple.framework.IOKit (2.0.2 - 1726.148.1) <0A9D244C-AECC-3D29-86DE-4F3B04F8DD25> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff42892000 -     0x7fff428a1ff7  com.apple.opengl (17.10.22 - 17.10.22) <AEF724FB-395B-3887-B36D-79AE5926C7DD> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL

**Comment by drhelius** [comment] 2021-09-08 10:20
Ok that gives some light.

SDL lib 2.0.16 is included in the bundled but It looks like is not looking in the right place for you (Gearcoleco.app/Contents/Frameworks).

Let me take a look, I'm running Big Sur (11.5.2) and Apple may have changed something (as usual).

**Comment by drhelius** [comment] 2021-09-08 10:48
Sorry for the confusion. 

I made a bundle for you to test [Gearcoleco.app.zip](https://github.com/drhelius/Gearcoleco/files/7128215/Gearcoleco.app.zip)

Let me know if this work for you

**Comment by Shrapnel21** [comment] 2021-09-08 10:52
It now looks for the DYLD where it should, but still fails.
Oh well, don't worry. I guess there something wonky with my install, probably. Thanks again! =)

- - - - -
Process:               gearcoleco [8895]
Path:                  /Users/USER/*/Gearcoleco.app/Contents/MacOS/gearcoleco
Identifier:            gearcoleco
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ??? [8894]
User ID:               501

Date/Time:             2021-09-08 12:50:36.388 +0200
OS Version:            Mac OS X 10.15.7 (19H1323)
Report Version:        12
Anonymous UUID:        E2DAB20E-07ED-8A95-C824-97B4344E85E3

Sleep/Wake UUID:       9B14C137-A44C-4BC7-BD89-9402C884BFD3

Time Awake Since Boot: 6500 seconds
Time Since Wake:       870 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @Gearcoleco.app/Contents/Frameworks/libSDL2-2.0.0.dylib
  Referenced from: /Users/USER/*/Gearcoleco.app/Contents/MacOS/./gearcoleco
  Reason: image not found

**Comment by drhelius** [comment] 2023-07-11 17:43
Closing as can’t reproduce, don’t hesitate to open it again if you have more info.

**Closed by drhelius** 2023-07-11 17:43 UTC
